Sopro/Models/Person.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sopro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Vorname { get; set; }
        public int Abteilungid { get; set; }
        public string Passwort { get; set; }
    }
}

Sopro/Models/SoproDBModel.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sopro.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SoproDBEntities : DbContext
    {
        public SoproDBEntities()
            : base("name=SoproDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Vertrag> Vertrags { get; set; }
    }
}

Sopro/Models/SoproDBModel.Designer.cs
// Die T4-Codegenerierung ist für Modell '\\mac\home\documents\visual studio 2015\Projects\Sopro\Sopro\Models\SoproDBModel.edmx' aktiviert. 
// Um die Generierung von Legacycode zu aktivieren, ändern Sie den Wert der Designer-Eigenschaft 'Code Generation Strategy'
// in 'Legacy ObjectContext'. Diese Eigenschaft wird im Eigenschaftenfenster angezeigt, wenn das Modell
// im Designer geöffnet ist.

// Wenn keine Kontextklasse und keine Entitätsklassen generiert wurden, kann dies daran liegen, dass Sie ein leeres Modell erstellt, aber
// noch nicht die gewünschte Entity Framework-Version ausgewählt haben. Um eine Kontextklasse und
// Entitätsklassen für das Modell zu generieren, öffnen Sie das Modell im Designer, klicken mit der rechten Maustaste auf die Designeroberfläche, und
// wählen 'Modell aus der Datenbank aktualisieren', 'Datenbank aus Modell generieren' oder 'Codegenerierungselement
// hinzufügen' aus.

Sopro/Models/SoproDBModel.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

Sopro/Models/Vertrag.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sopro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vertrag
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Typ { get; set; }
        public string Typ_2 { get; set; }
        public System.DateTime Datum { get; set; }
        public System.DateTime Beginn { get; set; }
        public System.DateTime Ende { get; set; }
    }
}

Sopro/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sopro.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Sopro/Controllers/VertragsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sopro.Models;

namespace Sopro.Controllers
{
    public class VertragsController : Controller
    {
        private SoproDBEntities db = new SoproDBEntities();


        //GET: Home

        public ActionResult Home()
        {
            return View();
        }
        
        // GET: Vertrags
        public ActionResult Overview()
        {
            return View(db.Vertrags.ToList());
        }

        // GET: Vertrags/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vertrag vertrag = db.Vertrags.Find(id);
            if (vertrag == null)
            {
                return HttpNotFound();
            }
            return View(vertrag);
        }

        // GET: Vertrags/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Vertrags/Create
        // Aktivieren Sie zum Schutz vor übermäßigem Senden von Angriffen die spezifischen Eigenschaften, mit denen eine Bindung erfolgen soll. Weitere Informationen 
        // finden Sie unter http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Typ,Typ_2,Datum,Beginn,Ende")] Vertrag vertrag)
        {
            if (ModelState.IsValid)
            {
                db.Vertrags.Add(vertrag);
                db.SaveChanges();
                return RedirectToAction("Overview");
            }

            return View(vertrag);
        }

        // GET: Vertrags/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vertrag vertrag = db.Vertrags.Find(id);
            if (vertrag == null)
            {
                return HttpNotFound();
            }
            return View(vertrag);
        }

        // POST: Vertrags/Edit/5
        // Aktivieren Sie zum Schutz vor übermäßigem Senden von Angriffen die spezifischen Eigenschaften, mit denen eine Bindung erfolgen soll. Weitere Informationen 
        // finden Sie unter http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Typ,Typ_2,Datum,Beginn,Ende")] Vertrag vertrag)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vertrag).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Overview");
            }
            return View(vertrag);
        }

        // GET: Vertrags/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vertrag vertrag = db.Vertrags.Find(id);
            if (vertrag == null)
            {
                return HttpNotFound();
            }
            return View(vertrag);
        }

        // POST: Vertrags/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Vertrag vertrag = db.Vertrags.Find(id);
            db.Vertrags.Remove(vertrag);
            db.SaveChanges();
            return RedirectToAction("Overview");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sopro/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/css/bootstrap.css" rel="stylesheet">
    <title>Startseite</title>
</head>
<body>
    <container class="row">
        <header class="col col-md-8 col-md-offset-2">
            <h1>Über den Link gehts zur Vetragsliste</h1>
        </header>
        <content class="col col-md-8 col-md-offset-2">
            <p>
                @Html.ActionLink("Zur Übersicht", "../Vertrags/Home")
            </p>
        </content>

    </container>
    
</body>
</html>

Sopro/Views/Vertrags/Create.cshtml
@model Sopro.Models.Vertrag

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Vertrag</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Typ, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Typ, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Typ, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Typ_2, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Typ_2, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Typ_2, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Datum, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Datum, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Datum, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Beginn, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Beginn, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Beginn, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Ende, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Ende, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Ende, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Zurück zur Übersicht", "overview")
    </div>
</body>
</html>

Sopro/Views/Vertrags/Delete.cshtml
@model Sopro.Models.Vertrag

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Vertrag</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Typ)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Typ)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Typ_2)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Typ_2)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Datum)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Datum)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Beginn)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Beginn)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Ende)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Ende)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Zurück zur Übersicht", "overview")
            </div>
        }
    </div>
</body>
</html>

Sopro/Views/Vertrags/Details.cshtml
@model Sopro.Models.Vertrag

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Vertrag</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Typ)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Typ)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Typ_2)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Typ_2)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Datum)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Datum)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Beginn)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Beginn)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Ende)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Ende)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Zurück zur Übersicht", "overview")
    </p>
</body>
</html>

Sopro/Views/Vertrags/Edit.cshtml
@model Sopro.Models.Vertrag

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Vertrag</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Typ, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Typ, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Typ, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Typ_2, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Typ_2, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Typ_2, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Datum, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Datum, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Datum, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Beginn, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Beginn, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Beginn, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Ende, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Ende, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Ende, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("ZUrück zur Übersicht", "overview")
    </div>
</body>
</html>

Sopro/Views/Vertrags/Home.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Home</title>
    <link href="~/css/bootstrap.css" rel="stylesheet">
</head>
<body>
    <dic class="row">
        <div class="col col-md-10 col-md-offset-1">
            <div class="row">
                <div class="col-md-12">
                    <ul class="nav nav-tabs">
                        <li role="presentation" class="active">@Html.ActionLink("Home", "Home")</li>
                        <li role="presentation">@Html.ActionLink("Verträge", "overview")</li>
                        <li role="presentation">@Html.ActionLink("Aufgaben", "Aufgaben")</li>
                        <li role="presentation">@Html.ActionLink("Admin", "Admin")</li>
                        <li role="presentation" style="float:right"><input class="btn btn-info" id="Suchen_senden" type="submit" value="Suchen" /></li>
                        <li role="presentation" style="float:right"><input id="Suchen" type="text" class="form-control" placeholder="Suche" /></li>

                    </ul>
                </div>
            </div>
        </div>
    </dic><!--ende header-->
    <div class="row">
        <div class="col col-md-10 col-md-offset-1">
            <div class="col col-md-6">
                <table class="table">
                    <thead>Liste 1</thead>
                    <tr>
                        <th>Vertragsname</th>
                        <th>Typ1</th>
                        <th>Typ2</th>
                    </tr>
                    <tr>
                        <td>Vertrag 1</td>
                        <td>Handyvertrag</td>
                        <td>Persönlich</td>
                    </tr>
                    <tr>
                        <td>Vertrag 2</td>
                        <td>Mietvertrag</td>
                        <td>Persönlich</td>
                    </tr>
                </table>
            </div>
            <div class="col col-md-6">
                <table class="table">
                    <thead>Liste 2</thead>
                    <tr>
                        <th>Vertragsname</th>
                        <th>Typ1</th>
                        <th>Typ2</th>
                    </tr>
                    <tr>
                        <td>Vertrag 1</td>
                        <td>Handyvertrag</td>
                        <td>Persönlich</td>
                    </tr>
                    <tr>
                        <td>Vertrag 2</td>
                        <td>Mietvertrag</td>
                        <td>Persönlich</td>
                    </tr>
                </table>
            </div>
            
        </div><!--Ende Content-->
    </div>
        
    
</body>
</html>

Sopro/Views/Vertrags/overview.cshtml
@model IEnumerable<Sopro.Models.Vertrag>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/css/bootstrap.css" rel="stylesheet">

    <title>Index</title>
</head>
<body>
    <container>
        <dic class="row">
            <div class="col col-md-10 col-md-offset-1">
                <div class="row">
                    <div class="col-md-12">
                        <ul class="nav nav-tabs">
                            <li role="presentation">@Html.ActionLink("Home", "Home")</li>
                            <li role="presentation" class="active">@Html.ActionLink("Verträge", "overview")</li>
                            <li role="presentation">@Html.ActionLink("Aufgaben", "Aufgaben")</li>
                            <li role="presentation">@Html.ActionLink("Admin", "Admin")</li>
                            <li role="presentation" style="float:right"><input class="btn btn-info" id="Suchen_senden" type="submit" value="Suchen" /></li>
                            <li role="presentation" style="float:right"><input id="Suchen" type="text" class="form-control" placeholder="Suche" /></li>

                        </ul>
                        <br />
                        <span style="float: right">
                            <input id="sucherErweitert" type="checkbox" />
                            Erweiterte Suche
                        </span>
                    </div>
                </div>
            </div>
        </dic><!--ende header-->
        
        <content class="row">
            <div class="col col-md-8 col-md-offset-2">
                <p>
                    <a href="@Url.Action("create", "Vertrags")" class="btn btn-info">Neuen Vertrag anlegen</a>
                    <a href="#" class="btn btn-info">Auswertung</a>
                    <span style="float: right">
                        <label class="checkbox-inline">
                            <input type="checkbox" id="inlineCheckbox1" value="option1"> unvollst.
                        </label>
                        <label class="checkbox-inline">
                            <input type="checkbox" id="inlineCheckbox2" value="option2"> 
                            <select id="Select1">
                            <option>Option 1</option>
                            <option>Option 2</option>
                            </select> Typ 1
                        </label>
                        <label class="checkbox-inline">
                            <input type="checkbox" id="inlineCheckbox3" value="option3"> Typ 2
                        </label>
                        <br />
                        <label class="checkbox-inline">
                            <input type="checkbox" id="inlineCheckbox1" value="option1"> unvollst.
                        </label>
                        <label class="checkbox-inline">
                            <input type="checkbox" id="inlineCheckbox3" value="option3">
                            <select id="Select2">
                                <option>Option 1</option>
                                <option>Option 2</option>
                            </select> Typ 2
                        </label>
                        <label class="checkbox-inline">
                            <input type="checkbox" id="inlineCheckbox2" value="option2"> Typ 1
                        </label>
                        
                    </span>
                    

                </p>
                <table class="table">
                    <tr>
                        <th>
                             Name <span class="glyphicon glyphicon-chevron-down">&nbsp; </span>
                        </th>
                        <th>
                            Typ
                        </th>
                        <th>
                            Untertyp
                        </th>
                        <th>
                            Erstellt am
                        </th>
                        <th>
                            Beginn
                        </th>
                        <th>
                            Ende
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
            {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Typ)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Typ_2)
                            </td>
                            <td>
                                @{
                                    var format = "MM/dd/yyyy";
                                    DateTime datum = item.Datum;
                                    var str = datum.ToString(format);
                                }
                               @str
                            </td>
                            <td>
                                @{
                                    datum = item.Beginn;
                                    str = datum.ToString(format);
                                }
                                @str
                            </td>
                            <td>
                                @{
                                    datum = item.Ende;
                                    str = datum.ToString(format);
                                }
                                @str
                            </td>
                            <td>
                                @Html.ActionLink("Ändern", "Edit", new { id = item.Id }) |
                                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                                @Html.ActionLink("Löschen", "Delete", new { id = item.Id })
                            </td>
                        </tr>
                                    }

                </table>
            </div>
            
            
        </content>
       
    </container>
    
</body>
</html>